[project]
name = "repl-nix-spiralmaster"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.58.1",
    "requests>=2.32.3",
    "streamlit>=1.41.1",
]
